# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('project_type', models.CharField(choices=[('Med', 'Medical'), ('Lit', 'Literature')], default='NO', max_length=200)),
                ('project_link', models.URLField(default='error.html')),
                ('likes_total', models.IntegerField(default=0)),
                ('comments_total', models.IntegerField(default=0)),
                ('shares_total', models.IntegerField(default=0)),
                ('following_total', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
