# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170327_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_link',
        ),
    ]
