# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170330_0653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_like',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='project_like',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_like',
            name='user',
        ),
        migrations.DeleteModel(
            name='project_like',
        ),
    ]
