# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170330_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20, null=True)),
                ('file_project', models.FileField(default=True, upload_to='project_data')),
            ],
        ),
    ]
