# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_file_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_project_link', models.FileField(default=True, upload_to='project_data')),
            ],
        ),
        migrations.DeleteModel(
            name='file_modal',
        ),
    ]
