# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170401_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='file_project_link',
            field=models.FileField(default=True, upload_to='project_sih/static/user_media'),
        ),
    ]
