# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profile_link', models.URLField(default='/welcome_user')),
                ('dob', models.DateField(null=True)),
                ('intro', models.CharField(max_length=200, null=True)),
                ('photo_link', models.URLField(default='/static/sitewide/anonymous-male.png')),
                ('followers_total', models.IntegerField(default=0)),
                ('following_total', models.IntegerField(default=0)),
                ('projects_total', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
