# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_and_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='photo_link',
            field=models.URLField(default='/static/images/anonymous-male.png'),
        ),
    ]
